import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  project: [{type: 'autogenerated', dirName: 'project'}],
  mute8: [{type: 'autogenerated', dirName: 'mute8'}],
  mute8react: [{type: 'autogenerated', dirName: 'mute8-react'}],
  mute8solid: [{type: 'autogenerated', dirName: 'mute8-solid'}],
  mute8plugins: [{type: 'autogenerated', dirName: 'mute8-plugins'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
