import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 The sidebars can be generated from the filesystem, or explicitly defined here.
 */
const sidebars: SidebarsConfig = {
  project: [{type: 'autogenerated', dirName: 'project'}],
  mute8: [{type: 'autogenerated', dirName: 'mute8'}],
  'mute8-angular': [{type: 'autogenerated', dirName: 'mute8-angular'}],
  'mute8-preact': [{type: 'autogenerated', dirName: 'mute8-preact'}],
  'mute8-vue': [{type: 'autogenerated', dirName: 'mute8-vue'}],
  'mute8-react': [{type: 'autogenerated', dirName: 'mute8-react'}],
  'mute8-solid': [{type: 'autogenerated', dirName: 'mute8-solid'}],
  'mute8-plugins': [{type: 'autogenerated', dirName: 'mute8-plugins'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
